### ISSUE TITLE
Дисейблить меню направленности при точечном репорте

### ISSUE THREAD

**Issue by RipZ** [coilamo/feedwazerussia#16]
При установке точечного репорта запретить выбор направления. Автоматически подставлять BOTH_DIRECTIONS при создании точечного репорта.

**Comment by alexletov** [comment]
https://github.com/coilamo/feedwazerussia/pull/17

**Comment by RipZ** [comment]
![image](https://cloud.githubusercontent.com/assets/54253/26513905/eb2edb0e-4276-11e7-951e-210284b537cc.png)
в таком случае тогда уж и убрать если возможно сам заголовок Direction, хотя не принципиально?

**Comment by alexletov** [comment]
Есть такое, но все же предлагаю дизайн позже подкручивать.
