### ISSUE TITLE
Локализация

### ISSUE THREAD

**Issue by RipZ** [coilamo/feedwazerussia#23]
Прикрутить локализацию к выводу в таблице.
BOTH_DIRECTIONS => Оба направления
HAZARD_ON_ROAD => Опасность на дороге

ну и всё, что там есть.

**Comment by RipZ** [comment]
Комментарий для автора, не отображается на карте и в клиенте
Описание: Заполните краткое описание, если необходимо для отображения в клиенте…

**Comment by alexletov** [comment]
#37
